/* ===== v3.5.3 sync/audit integrity ===== */
const V353_VERSION='3.5.3';
function v353AuditKey(a){return a?.auditId||`AUDX-${v2Hash32(`${a?.timestamp||''}|${a?.operation||''}|${a?.userId||a?.user||''}|${a?.deviceId||''}|${a?.uid||a?.recordId||''}|${a?.field||''}|${a?.oldValue||''}|${a?.newValue||''}`)}`}
function v353ExchangeKey(x){return x?.id||`EXX-${v2Hash32(`${x?.type||''}|${x?.timestamp||''}|${x?.userId||x?.user||''}|${x?.deviceId||''}|${x?.sourceExportId||''}`)}`}
function v353ContributorCatalog(){
 const m=new Map();const put=(id,name,role='')=>{id=String(id||'').trim();if(!id)return;const old=m.get(id)||{userId:id,name:name||id,role:role||''};if(name)old.name=name;if(role)old.role=role;m.set(id,old)};
 for(const u of state.users||[])put(u.id,u.name,u.role);
 for(const a of state.audit||[])put(a.userId||v330UserIdByName(a.user),a.user,a.userRole||'');
 for(const x of state.exchangeLog||[])put(x.userId||v330UserIdByName(x.user),x.user,x.userRole||'');
 for(const r of state.records||[]){put(r.creatorUserId,r.createdBy||r.user,'');put(r.updatedByUserId,r.updatedBy||'','')}
 for(const d of state.deletedRecords||[])put(d.deletedByUserId,d.deletedBy,'');
 return [...m.values()];
}
function v353MergeRemoteAudit(rows,importId,sourceDevice){let added=0;const seen=new Set((state.audit||[]).map(v353AuditKey));for(const raw of rows||[]){const a=clone(raw||{});if(!a.timestamp||!a.operation)continue;a.auditId=a.auditId||v353AuditKey(a);const k=v353AuditKey(a);if(seen.has(k))continue;a.userId=a.userId||v330UserIdByName(a.user)||'';a.remoteOriginal='نعم';a.importedVia=importId||'';a.originDeviceId=a.originDeviceId||a.deviceId||sourceDevice?.deviceId||'';a.originDeviceName=a.originDeviceName||a.deviceName||sourceDevice?.deviceName||'';state.audit.push(a);seen.add(k);added++}state.audit.sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')));state.audit=state.audit.slice(0,20000);return added}
function v353MergeRemoteExchange(rows,importId,sourceDevice){let added=0;const seen=new Set((state.exchangeLog||[]).map(v353ExchangeKey));for(const raw of rows||[]){const x=clone(raw||{});if(!x.type||!x.timestamp)continue;x.id=x.id||v353ExchangeKey(x);const k=v353ExchangeKey(x);if(seen.has(k))continue;x.remoteOriginal='نعم';x.importedVia=importId||'';x.originDeviceId=x.originDeviceId||x.deviceId||sourceDevice?.deviceId||'';state.exchangeLog.push(x);seen.add(k);added++}state.exchangeLog.sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')));state.exchangeLog=state.exchangeLog.slice(0,5000);return added}
function v353TombKey(d){return d?.tombstoneId||`DELX-${v2Hash32(`${d?.uid||''}|${d?.deletedAt||''}|${d?.deletedByUserId||d?.deletedBy||''}|${d?.deviceId||''}`)}`}
function v353MergeRemoteDeletionHistory(preview){let added=0;const seen=new Set((state.deletedRecords||[]).map(v353TombKey));for(const it of preview?.items||[]){if(it.kind!=='deletion'||it.decision!=='replace')continue;const inc=clone(it.incoming||{});if(!inc.uid)continue;if(it.historyOnly){inc.tombstoneId=inc.tombstoneId||v353TombKey(inc);const k=v353TombKey(inc);if(seen.has(k))continue;inc.sourceImportId=preview.importId;inc.remoteOriginal='نعم';if(inc.record)v330EnsureRecord(inc.record);state.deletedRecords.unshift(inc);seen.add(k);added++;continue}const localTomb=(state.deletedRecords||[]).find(d=>d.sourceImportId===preview.importId&&d.uid===it.uid);if(localTomb){localTomb.sourceTombstone=inc;localTomb.sourceDeletedAt=inc.deletedAt||'';localTomb.sourceDeletedBy=inc.deletedBy||'';localTomb.sourceDeletedByUserId=inc.deletedByUserId||'';localTomb.sourceDeviceId=inc.deviceId||preview.sourceDevice?.deviceId||''}}
 return added}
const v353BuildSyncBase=v2BuildSyncPackage;
v2BuildSyncPackage=function(){const pkg=v353BuildSyncBase();pkg.schemaVersion=V2_SCHEMA_VERSION;pkg.auditTrail=clone(state.audit||[]).slice(0,20000);pkg.exchangeHistory=clone(state.exchangeLog||[]).slice(0,5000);pkg.deletedRecords=clone(state.deletedRecords||[]).slice(0,5000);pkg.contributors=v353ContributorCatalog();pkg.capabilities={...(pkg.capabilities||{}),fullAudit:true,fullDeleteSnapshot:true,contributorIdentity:true,workNumberDuplicateReview:true};return pkg};

const v353StageBase=v2StageImport;
v2StageImport=function(pkg){const p=v353StageBase(pkg);p.remoteAudit=clone(pkg.auditTrail||[]);p.remoteExchange=clone(pkg.exchangeHistory||[]);p.remoteContributors=clone(pkg.contributors||[]);p.remoteDeleted=clone(pkg.deletedRecords||[]);
 for(const it of p.items||[]){if(it.kind!=='duplicate')continue;const sameSubject=v330NormSubject(it.local?.subject)===v330NormSubject(it.incoming?.subject);it.subjectConflict=!sameSubject;const lu=it.local?.creatorUserId||'',iu=it.incoming?.creatorUserId||p.exportedBy?.userId||'';it.sameContributor=!!(lu&&iu&&lu===iu);it.duplicateReason=sameSubject?(it.sameContributor?'نفس رقم العمل والموضوع ونفس معرف المستخدم':'نفس رقم العمل والموضوع من مستخدم مختلف'):'نفس رقم العمل لكن الموضوع مختلف';it.decision=sameSubject?'merge':'side'}
 const itemKeys=new Set((p.items||[]).filter(x=>x.kind==='deletion').map(x=>`${x.uid}|${x.incoming?.tombstoneId||''}`));const localDeleted=new Set((state.deletedRecords||[]).map(v353TombKey));for(const d0 of pkg.deletedRecords||[]){const d=clone(d0);const k=v353TombKey(d);const ik=`${d.uid}|${d.tombstoneId||''}`;if(itemKeys.has(ik)||localDeleted.has(k))continue;const local=state.records.find(r=>r.uid===d.uid)||null;if(!local){p.items.push({kind:'deletion',uid:d.uid,local:null,incoming:d,decision:'replace',historyOnly:true,diff:{fields:[{field:'deleted',label:'الحذف',oldValue:'غير موجود على هذا الجهاز',newValue:'محذوف على جهاز المصدر'}],newProgress:[]}});itemKeys.add(ik)}}
 p.fieldCounts=v330FieldCounts(p.items||[]);state.importPreview=p;render();return p};

const v353ImportItemBase=v330ImportItemHtml;
v330ImportItemHtml=function(it,p){if(it.kind==='deletion'&&it.historyOnly){const idx=p.items.indexOf(it),r=it.incoming?.record||{};return `<article class="v330-import-item"><div class="v330-import-item-head"><div><strong>سجل محذوف على جهاز الزميل · ${esc(r.recordNo||r.id||it.uid||'')}</strong><div>${esc(r.subject||'')}</div><div class="v330-import-source">حذفه: ${esc(it.incoming?.deletedBy||'—')} (${esc(it.incoming?.deletedByUserId||'—')}) · ${esc(String(it.incoming?.deletedAt||'').replace('T',' ').slice(0,16))}</div></div><span class="badge st-cancel">حذف محفوظ</span></div><div class="v2-delete-warning">السجل غير موجود حاليًا على جهازك. اعتماد الخيار سيحفظ نسخة الحذف الكاملة في سجل التغييرات دون إنشاء سجل فعلي جديد.</div><div class="v330-decisions"><button class="btn ${it.decision==='replace'?'':'secondary'}" data-action="v2-import-decision" data-index="${idx}" data-decision="replace">حفظ أثر الحذف</button><button class="btn ${it.decision==='keep'?'':'secondary'}" data-action="v2-import-decision" data-index="${idx}" data-decision="keep">تجاهل</button></div></article>`}
 if(it.kind==='duplicate'&&it.subjectConflict){const idx=p.items.indexOf(it),local=it.local||{},incoming=it.incoming||{};return `<article class="v330-import-item"><div class="v330-import-item-head"><div><strong>نفس رقم العمل — الموضوع مختلف · ${esc(local.recordNo||incoming.recordNo||'')}</strong><div>الحالي: ${esc(local.subject||'—')}</div><div>الوارد: ${esc(incoming.subject||'—')}</div><div class="v330-import-source">الحالي: ${esc(local.createdBy||local.user||'—')} (${esc(local.creatorUserId||'—')}) · الوارد: ${esc(incoming.createdBy||p.exportedBy?.name||'—')} (${esc(incoming.creatorUserId||p.exportedBy?.userId||'—')})</div></div><span class="badge st-late">تعارض</span></div>${v2RenderDiff(it.diff||{fields:[],newProgress:[]})}<div class="v2-delete-warning">لن يتم الدمج تلقائيًا لأن الموضوع مختلف رغم تطابق رقم العمل. اختر اعتماد الوارد أو الاحتفاظ بالحالي.</div><div class="v330-decisions"><button class="btn ${it.decision==='replace'?'':'secondary'}" data-action="v2-import-decision" data-index="${idx}" data-decision="replace">اعتماد الوارد</button><button class="btn ${it.decision==='keep'?'':'secondary'}" data-action="v2-import-decision" data-index="${idx}" data-decision="keep">الاحتفاظ بالحالي</button></div></article>`}
 return v353ImportItemBase(it,p)};

const v353ApplyImportBase=v2ApplyImport;
v2ApplyImport=async function(){const preview=state.importPreview?clone(state.importPreview):null;if(preview){const unresolved=(preview.items||[]).filter(it=>it.kind==='duplicate'&&it.subjectConflict&&!['replace','keep'].includes(it.decision));if(unresolved.length){showToast('يوجد رقم عمل مكرر بموضوع مختلف. اختر اعتماد الوارد أو الاحتفاظ بالحالي قبل إكمال الدمج.','warn');return}}
 await v353ApplyImportBase();if(!preview)return;const remoteAudit=v353MergeRemoteAudit(preview.remoteAudit||[],preview.importId,preview.sourceDevice);const remoteExchange=v353MergeRemoteExchange(preview.remoteExchange||[],preview.importId,preview.sourceDevice);const remoteDeleted=v353MergeRemoteDeletionHistory(preview);if(state.lastImportReport){state.lastImportReport.remoteAuditCount=remoteAudit;state.lastImportReport.remoteExchangeCount=remoteExchange;state.lastImportReport.remoteDeletedHistoryCount=remoteDeleted;state.lastImportReport.auditTransferred='نعم'}await saveExcel('تم حفظ سجل تدقيق ونشاط جهاز الزميل');render()};

v330ActivityStats=function(){const out=new Map();const put=(id,name,role='')=>{id=String(id||'').trim();if(!id)return null;if(!out.has(id))out.set(id,{u:{id,name:name||id,role:role||'مستخدم مساهم',contributor:true},adds:0,edits:0,deletes:0,exports:0,imports:0,progress:0,records:0,tasks:0});else{const x=out.get(id);if(name)x.u.name=name;if(role)x.u.role=role}return out.get(id)};for(const u of state.users||[])put(u.id,u.name,u.role);for(const a of state.audit||[])put(a.userId||v330UserIdByName(a.user),a.user,a.userRole||'');for(const x of state.exchangeLog||[])put(x.userId||v330UserIdByName(x.user),x.user,x.userRole||'');for(const r of state.records||[]){v330EnsureRecord(r);const x=put(r.creatorUserId,r.createdBy||r.user,'');if(x){x.records++;if(r.type==='مهمة')x.tasks++}}for(const a of state.audit||[]){const x=put(a.userId||v330UserIdByName(a.user),a.user,a.userRole||'');if(!x)continue;const op=String(a.operation||'');if(op==='إضافة'||op==='إضافة عمل جديد')x.adds++;if(op.includes('مجرى متابعة')||op.includes('مجريات متابعة'))x.progress++;if(op==='تعديل'||op==='تغيير حقل'||op.includes('اعتماد تعديل')||op.includes('دمج سجل')||op==='تعديل مجرى متابعة')x.edits++;if(op.includes('حذف'))x.deletes++}for(const l of state.exchangeLog||[]){if(l.undone)continue;const x=put(l.userId||v330UserIdByName(l.user),l.user,l.userRole||'');if(!x)continue;if(l.type==='تصدير')x.exports++;else if(l.type==='استيراد')x.imports++}return [...out.values()].sort((a,b)=>String(a.u.name||'').localeCompare(String(b.u.name||''),'ar'))};

const v353DataBase=renderData;renderData=function(){return v353DataBase().replace(/3\.5\.2/g,'3.5.3').replace(/3\.5\.1/g,'3.5.3')};
/* ===== end v3.5.3 ===== */